# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AwesomeMusic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  # pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  # pod 'Firebase/Crash'
  pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  # pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/RemoteConfig'
  # pod 'Firebase/Storage'
  # Pods for AwesomeMusic

  target 'AwesomeMusic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AwesomeMusic-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeMusic-tvOS

end
